-- Me-Antsena / Supabase schema
-- Exécuter ce fichier dans Supabase Dashboard > SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text not null default '',
  last_name text not null default '',
  email text not null unique,
  phone text,
  role text not null default 'user' check (role in ('user','admin')),
  status text not null default 'active' check (status in ('active','suspended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text default '🏷️'
);
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text not null default '',
  description text not null default '',
  price numeric(14,2) not null check(price >= 0),
  stock integer not null default 0 check(stock >= 0),
  category_id bigint references public.categories(id) on delete set null,
  images jsonb not null default '[]'::jsonb,
  tags jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.products add column if not exists brand text not null default '';
create table if not exists public.addresses (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  label text not null default 'Livraison', street text not null, created_at timestamptz not null default now()
);
create table if not exists public.favorites (
  user_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(), primary key(user_id,product_id)
);
create table if not exists public.interactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  type text not null, value numeric(12,2), search_query text, recommendation_source text,
  created_at timestamptz not null default now()
);
alter table public.interactions add column if not exists search_query text;
alter table public.interactions add column if not exists recommendation_source text;
create table if not exists public.recommendations (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('collaborative','content','hybrid')),
  product_id bigint not null references public.products(id) on delete cascade,
  score numeric(12,6) not null default 0,
  created_at timestamptz not null default now(),
  unique(type, product_id)
);
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  rating integer not null check(rating between 1 and 5), comment text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,product_id)
);
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete restrict,
  address_id bigint references public.addresses(id) on delete set null,
  payment_method text, delivery_method text,
  status text not null default 'pending' check(status in ('pending','paid','shipped','delivered','cancelled')),
  total numeric(14,2) not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null, unit_price numeric(14,2) not null, quantity integer not null check(quantity > 0)
);

create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,first_name,last_name,email,phone)
  values(new.id,coalesce(new.raw_user_meta_data->>'first_name',''),coalesce(new.raw_user_meta_data->>'last_name',''),new.email,coalesce(new.raw_user_meta_data->>'phone',''))
  on conflict(id) do update set email=excluded.email;
  return new;
end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='admin' and status='active');
$$;

create or replace function public.admin_set_user_status(p_user_id uuid, p_status text) returns public.profiles
language plpgsql security definer set search_path=public as $$
declare v public.profiles;
begin
  if not public.is_admin() then raise exception 'Accès administrateur requis'; end if;
  if p_status not in ('active','suspended') then raise exception 'Statut invalide'; end if;
  update public.profiles set status=p_status,updated_at=now() where id=p_user_id returning * into v;
  if not found then raise exception 'Utilisateur introuvable'; end if;
  return v;
end; $$;
revoke all on function public.admin_set_user_status(uuid,text) from public;
grant execute on function public.admin_set_user_status(uuid,text) to authenticated;

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.addresses enable row level security;
alter table public.favorites enable row level security;
alter table public.interactions enable row level security;
alter table public.recommendations enable row level security;
alter table public.reviews enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select using (id=auth.uid() or public.is_admin());
drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles for update using (id=auth.uid()) with check (id=auth.uid());
revoke update on public.profiles from authenticated;
grant update(first_name,last_name,phone) on public.profiles to authenticated;

drop policy if exists categories_read on public.categories; create policy categories_read on public.categories for select using(true);
drop policy if exists categories_admin on public.categories; create policy categories_admin on public.categories for all using(public.is_admin()) with check(public.is_admin());

drop policy if exists products_read on public.products; create policy products_read on public.products for select using(true);
drop policy if exists products_admin on public.products; create policy products_admin on public.products for all using(public.is_admin()) with check(public.is_admin());

drop policy if exists addresses_own on public.addresses; create policy addresses_own on public.addresses for all using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin());
drop policy if exists favorites_own on public.favorites; create policy favorites_own on public.favorites for all using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists interactions_own on public.interactions; create policy interactions_own on public.interactions for all using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists interactions_admin_read on public.interactions; create policy interactions_admin_read on public.interactions for select using(public.is_admin());
drop policy if exists recommendations_read on public.recommendations; create policy recommendations_read on public.recommendations for select using(true);
drop policy if exists recommendations_admin on public.recommendations; create policy recommendations_admin on public.recommendations for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists reviews_read on public.reviews; create policy reviews_read on public.reviews for select using(true);
drop policy if exists reviews_write on public.reviews; create policy reviews_write on public.reviews for all using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists orders_read on public.orders; create policy orders_read on public.orders for select using(user_id=auth.uid() or public.is_admin());
drop policy if exists orders_admin_update on public.orders; create policy orders_admin_update on public.orders for update using(public.is_admin()) with check(public.is_admin());
drop policy if exists order_items_read on public.order_items; create policy order_items_read on public.order_items for select using(exists(select 1 from public.orders o where o.id=order_id and (o.user_id=auth.uid() or public.is_admin())));

create or replace function public.create_order(p_items jsonb,p_address_id bigint default null,p_payment_method text default null,p_delivery_method text default null)
returns public.orders language plpgsql security definer set search_path=public as $$
declare v_order public.orders; v_item jsonb; v_product public.products; v_qty integer; v_total numeric(14,2):=0;
begin
 if auth.uid() is null then raise exception 'Authentification requise'; end if;
 if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items)=0 then raise exception 'Panier vide'; end if;
 if p_address_id is not null and not exists(select 1 from public.addresses where id=p_address_id and user_id=auth.uid()) then raise exception 'Adresse invalide'; end if;
 insert into public.orders(user_id,address_id,payment_method,delivery_method,total) values(auth.uid(),p_address_id,p_payment_method,p_delivery_method,0) returning * into v_order;
 for v_item in select * from jsonb_array_elements(p_items) loop
   v_qty := (v_item->>'quantity')::integer;
   select * into v_product from public.products where id=(v_item->>'product_id')::bigint for update;
   if not found then raise exception 'Produit introuvable'; end if;
   if v_qty < 1 or v_qty > v_product.stock then raise exception 'Stock insuffisant pour %',v_product.name; end if;
   v_total := v_total + v_product.price * v_qty;
   insert into public.order_items(order_id,product_id,product_name,unit_price,quantity) values(v_order.id,v_product.id,v_product.name,v_product.price,v_qty);
   update public.products set stock=stock-v_qty,updated_at=now() where id=v_product.id;
 end loop;
 update public.orders set total=v_total where id=v_order.id returning * into v_order;
 return v_order;
exception when others then raise;
end; $$;

revoke all on function public.create_order(jsonb,bigint,text,text) from public;
grant execute on function public.create_order(jsonb,bigint,text,text) to authenticated;

insert into public.categories(name,icon) values
('Électronique','💻'),('Mode','👕'),('Maison','🏠'),('Sports','⚽'),('Livres','📚'),('Bijoux','💍'),('Beauté','💄'),('Auto','🚗'),('Alimentation','🛒') on conflict(name) do nothing;

insert into public.products(name,description,price,stock,category_id,images,tags)
select x.name,x.description,x.price,x.stock,c.id,x.images::jsonb,x.tags::jsonb from (values
  ('Casque Bluetooth SoundPro X1', 'Casque sans fil circum-aural avec réduction active du bruit, autonomie 30h et son haute fidélité.', 145000, 35, 'Électronique', '["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80"]', '["audio", "casque", "bluetooth"]'),
  ('Smartphone Pro Max 5G 128Go', 'Smartphone haut de gamme avec écran AMOLED 120Hz, triple capteur photo et processeur ultra-rapide.', 1250000, 18, 'Électronique', '["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80"]', '["smartphone", "mobile", "5g"]'),
  ('Montre Connectée FitPulse Pro', 'Montre intelligente avec suivi d''activité cardiaque, GPS intégré, notifications et écran tactile HD étanche.', 180000, 25, 'Électronique', '["https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80"]', '["montre", "sport", "smartwatch"]'),
  ('Clavier Mécanique Gamer RGB', 'Clavier gamer mécanique avec rétroéclairage RGB personnalisable, switches réactifs et frappe précise.', 160000, 20, 'Électronique', '["https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80"]', '["clavier", "gaming", "rgb"]'),
  ('Enceinte Portable Bluetooth Boom', 'Enceinte sans fil étanche IPX7 avec basses profondes, autonomie 15h et son surround 360°.', 95000, 40, 'Électronique', '["https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80"]', '["enceinte", "audio", "bluetooth"]'),
  ('Ordinateur Portable Ultrabook 14', 'PC portable ultra-fin et léger avec processeur performant, 16Go RAM, SSD 512Go et autonomie 12h.', 2100000, 12, 'Électronique', '["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=80"]', '["laptop", "ordinateur", "informatique"]'),
  ('Appareil Photo Reflex Numérique 4K', 'Boîtier photo reflex professionnel avec capteur 24.2 MP, enregistrement vidéo 4K et objectif 18-55mm.', 1950000, 8, 'Électronique', '["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80"]', '["photo", "camera", "reflex"]'),
  ('Écouteurs Sans Fil True Wireless Air', 'Écouteurs intra-auriculaires Bluetooth avec boîtier de charge rapide, réduction de bruit passive et micro HD.', 85000, 50, 'Électronique', '["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80"]', '["ecouteurs", "bluetooth", "audio"]'),
  ('Souris Ergonomique Sans Fil Precision', 'Souris sans fil silencieuse et ergonomique avec capteur optique haute précision et batterie rechargeable.', 55000, 45, 'Électronique', '["https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=800&q=80"]', '["souris", "accessoire", "bureau"]'),
  ('Tablette Tactile HD 10 Pouces', 'Tablette multimédia avec écran 2K lumineux, haut-parleurs stéréo et grande fluidité de navigation.', 820000, 15, 'Électronique', '["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80"]', '["tablette", "tactile", "multimedia"]'),
  ('Sac à Dos Urbain Canvas Premium', 'Sac à dos moderne et résistant en toile déperlante avec compartiment renforcé pour ordinateur 15 pouces.', 85000, 30, 'Mode', '["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80"]', '["sac", "mode", "urbain"]'),
  ('Veste en Jean Denim Classic', 'Veste en denim coupe droite classique, confectionnée en coton durable avec finitions soignées.', 110000, 22, 'Mode', '["https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80"]', '["veste", "denim", "mode"]'),
  ('T-shirt Col Rond en Coton Bio', 'T-shirt blanc essentiel en coton biologique peigné, doux au toucher et coupe ajustée confortable.', 35000, 80, 'Mode', '["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80"]', '["tshirt", "coton", "basique"]'),
  ('Sneakers Blanches Minimalistes', 'Baskets urbaines en cuir synthétique souple avec semelle coussinée pour un style chic et décontracté.', 135000, 28, 'Mode', '["https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=80"]', '["sneakers", "chaussures", "mode"]'),
  ('Robe d''Été Fluide Motif Floral', 'Robe légère à imprimé fleuri avec ceinture nouée à la taille, idéale pour les journées ensoleillées.', 95000, 20, 'Mode', '["https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=800&q=80"]', '["robe", "femme", "ete"]'),
  ('Manteau d''Hiver Coupe Droite en Laine', 'Manteau chaud et élégant doublé, col revers cranté et fermeture double boutonnage.', 220000, 14, 'Mode', '["https://images.unsplash.com/photo-1539533018447-63fcce667883?auto=format&fit=crop&w=800&q=80"]', '["manteau", "hiver", "chic"]'),
  ('Lunettes de Soleil Aviateur Polaros', 'Lunettes de soleil monture métal doré avec verres polarisés anti-reflet UV400 haute protection.', 45000, 40, 'Mode', '["https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80"]', '["lunettes", "accessoires", "soleil"]'),
  ('Sac à Main Élégant en Cuir Texturé', 'Sac bandoulière femme avec détails dorés, compartiment intérieur zippé et finition soignée.', 120000, 18, 'Mode', '["https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80"]', '["sac", "femme", "elegance"]'),
  ('Chemise Homme Casual en Lin', 'Chemise respirante à manches longues en lin et coton mélangés, col classique et coupe moderne.', 75000, 35, 'Mode', '["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80"]', '["chemise", "lin", "homme"]'),
  ('Chapeau Panama d''Été en Paille', 'Chapeau de paille tressée main avec ruban noir contrastant, idéal pour la plage et les promenades.', 40000, 25, 'Mode', '["https://images.unsplash.com/photo-1514327605112-b887c0e61c0a?auto=format&fit=crop&w=800&q=80"]', '["chapeau", "paille", "ete"]'),
  ('Lampe LED Moderne de Bureau', 'Lampe de table design minimaliste avec bras articulé, 3 températures de couleur et variateur tactile.', 45000, 50, 'Maison', '["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80"]', '["lampe", "eclairage", "maison"]'),
  ('Canapé Salon Scandinave 3 Places', 'Canapé contemporain habillé d''un tissu velours doux et robuste avec pieds en bois massif.', 850000, 6, 'Maison', '["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80"]', '["canape", "salon", "meuble"]'),
  ('Fauteuil Confort Lounge en Tissu', 'Fauteuil d''appoint confortable avec assise capitonnée et dossier ergonomique pour coin lecture.', 320000, 10, 'Maison', '["https://images.unsplash.com/photo-1580481077195-c3a82da91d9f?auto=format&fit=crop&w=800&q=80"]', '["fauteuil", "salon", "confort"]'),
  ('Table Basse Bois Massif et Métal', 'Table basse industrielle avec plateau en bois chaleureux et structure en métal laqué noir.', 210000, 12, 'Maison', '["https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?auto=format&fit=crop&w=800&q=80"]', '["table", "bois", "decoration"]'),
  ('Plante d''Intérieur Monstera en Pot', 'Plante verte naturelle Monstera Deliciosa fournie dans son cache-pot en céramique blanche.', 50000, 25, 'Maison', '["https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=800&q=80"]', '["plante", "nature", "deco"]'),
  ('Miroir Mural Rond Cadre Doré', 'Miroir décoratif circulaire diamètre 60cm avec cerclage métallique finition or brossé.', 85000, 18, 'Maison', '["https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80"]', '["miroir", "deco", "mural"]'),
  ('Set de Tasses Céramique Artisanale', 'Lot de 4 tasses en céramique émaillée fait main pour café, thé et chocolat chaud.', 38000, 35, 'Maison', '["https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80"]', '["tasse", "cuisine", "ceramique"]'),
  ('Bougie Parfumée Cire de Soja Vanille', 'Bougie artisanale en pot de verre ambré avec mèche en coton, parfum doux vanille et ambre.', 28000, 45, 'Maison', '["https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=800&q=80"]', '["bougie", "parfum", "ambiance"]'),
  ('Coussins Décoratifs Salon Bohème', 'Housse et garnissage de coussin texturé avec motifs ethniques tissés et fermeture zippée discrète.', 32000, 40, 'Maison', '["https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=800&q=80"]', '["coussin", "textile", "deco"]'),
  ('Tapis de Salon Géométrique Doux', 'Tapis moderne à poils ras au toucher soyeux, facile à nettoyer et motif géométrique tendance.', 175000, 15, 'Maison', '["https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&w=800&q=80"]', '["tapis", "salon", "sol"]'),
  ('Ballon de Football Officiel Match Pro', 'Ballon de football taille 5 thermocollé offrant une excellente trajectoire de vol et grande durabilité.', 75000, 45, 'Sports', '["https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=800&q=80"]', '["football", "ballon", "sport"]'),
  ('Baskets de Running Nike Revolution', 'Chaussures de running haute performance avec semelle amortissante réactive et empeigne respirante.', 185000, 22, 'Sports', '["https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80"]', '["running", "chaussures", "sport"]'),
  ('Tapis de Yoga Antidérapant Écologique', 'Tapis de yoga épais en matériau TPE recyclable, surface texturée antidérapante avec sangle de portage.', 48000, 35, 'Sports', '["https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=800&q=80"]', '["yoga", "fitness", "sol"]'),
  ('Paire d''Haltères Réglables en Fonte 20kg', 'Ensemble d''haltères modulables avec disques en fonte solide, barre moletée et écrous de serrage sûrs.', 130000, 18, 'Sports', '["https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80"]', '["musculation", "halteres", "fitness"]'),
  ('Gourde Isotherme Sport Inox 750ml', 'Bouteille réutilisable en inox double paroi gardant les boissons fraîches 24h ou chaudes 12h.', 35000, 60, 'Sports', '["https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80"]', '["gourde", "inox", "hydratation"]'),
  ('Vélo de Route Urbain Performance', 'Bicyclette légère à cadre aluminium, transmission 21 vitesses et freins à disque performants.', 950000, 7, 'Sports', '["https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=800&q=80"]', '["velo", "cyclisme", "transport"]'),
  ('Raquette de Tennis Tour Pro Compétition', 'Raquette de tennis équilibrée avec cadre en graphite, cordage haute tension et grip absorbant les chocs.', 165000, 16, 'Sports', '["https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?auto=format&fit=crop&w=800&q=80"]', '["tennis", "raquette", "match"]'),
  ('Ballon de Basketball Officiel Match', 'Ballon de basket en cuir composite grip optimal pour terrain intérieur ou bitume extérieur.', 65000, 30, 'Sports', '["https://images.unsplash.com/photo-1519861531473-9200262188bf?auto=format&fit=crop&w=800&q=80"]', '["basketball", "ballon", "terrain"]'),
  ('Corde à Sauter Rapide Speed Rope Crossfit', 'Corde à sauter avec câble acier gainé et roulements à billes fluides pour double-unders et cardio.', 22000, 55, 'Sports', '["https://images.unsplash.com/photo-1598971861713-54ad16a7e72e?auto=format&fit=crop&w=800&q=80"]', '["corde", "cardio", "fitness"]'),
  ('Gants de Boxe Entraînement Cuir Pro', 'Gants de boxe avec mousse multi-couches pour absorption des impacts et fermeture poignet velcro large.', 89000, 20, 'Sports', '["https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?auto=format&fit=crop&w=800&q=80"]', '["boxe", "gants", "combat"]'),
  ('Livre de Recettes : Saveurs du Monde', 'Plus de 100 recettes gourmandes et accessibles expliquées pas à pas avec de superbes photographies.', 42000, 40, 'Livres', '["https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=800&q=80"]', '["livre", "cuisine", "recettes"]'),
  ('Roman d''Aventure : L''Horizon Perdu', 'Un captivant roman d''exploration à suspense au cœur de contrées inexplorées et d''énigmes anciennes.', 32000, 50, 'Livres', '["https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=800&q=80"]', '["roman", "lecture", "aventure"]'),
  ('Guide de Développement Personnel & Succès', 'Méthodes pratiques et conseils psychologiques pour développer sa confiance, sa productivité et ses objectifs.', 36000, 45, 'Livres', '["https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=800&q=80"]', '["livre", "motivation", "succes"]'),
  ('Manuel Pratique du Développement Web Moderne', 'Guide complet pour apprendre JavaScript, React, Node.js et les architectures cloud modernes.', 65000, 25, 'Livres', '["https://images.unsplash.com/photo-1532012164546-f432f2e37257?auto=format&fit=crop&w=800&q=80"]', '["informatique", "web", "programmation"]'),
  ('Encyclopédie Illustrée de la Nature', 'Grand ouvrage relié richement documenté sur la biodiversité, les écosystèmes et la faune sauvage.', 78000, 15, 'Livres', '["https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80"]', '["encyclopedie", "nature", "animaux"]'),
  ('Histoire des Grandes Civilisations Anciennes', 'Une fresque historique détaillée sur les empires d''Égypte, de Mésopotamie, de Grèce et de Rome.', 48000, 30, 'Livres', '["https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=800&q=80"]', '["histoire", "civilisations", "culture"]'),
  ('Roman Graphique & Bande Dessinée Collector', 'Édition collector cartonnée avec planches originales illustrées couleur et récit captivant.', 55000, 20, 'Livres', '["https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=800&q=80"]', '["bd", "art", "graphique"]'),
  ('Guide Visuel & Photographie de Voyage', 'Ouvrage d''inspiration pour voyageurs et photographes avec cartes détaillées et astuces de terrain.', 52000, 22, 'Livres', '["https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=800&q=80"]', '["voyage", "photo", "decouverte"]'),
  ('Recueil de Poésie Contemporaine en Vers', 'Une anthologie poétique touchante sur les émotions humaines, la nature et le temps qui passe.', 28000, 35, 'Livres', '["https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&w=800&q=80"]', '["poesie", "litterature", "art"]'),
  ('Carnet de Notes en Cuir Vintage Fait Main', 'Carnet relié en cuir véritable avec pages en papier kraft épais pour écriture, croquis et journal intime.', 34000, 40, 'Livres', '["https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=800&q=80"]', '["carnet", "cuir", "ecriture"]'),
  ('Collier Pendentif Or Fin 18 Carats', 'Collier délicat en maille vénitienne plaqué or 18 carats avec pendentif serti d''un oxyde de zirconium.', 145000, 18, 'Bijoux', '["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80"]', '["collier", "or", "bijoux"]'),
  ('Bague Solitaire Diamant Argent Sterling 925', 'Bague intemporelle en argent massif 925 ornée d''une pierre centrale étincelante taille brillant.', 110000, 24, 'Bijoux', '["https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80"]', '["bague", "argent", "solitaire"]'),
  ('Boucles d''Oreilles Perles de Culture', 'Boucles d''oreilles pendantes agrémentées de perles d''eau douce nacrées et fermoir sécurisé.', 75000, 30, 'Bijoux', '["https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80"]', '["boucles", "perles", "femme"]'),
  ('Bracelet Jonc Doré Rigide Minimaliste', 'Bracelet jonc ouvert ajustable en acier inoxydable finition dorée miroir, hypoallergénique.', 60000, 35, 'Bijoux', '["https://images.unsplash.com/photo-1611591475152-4c09a3194026?auto=format&fit=crop&w=800&q=80"]', '["bracelet", "jonc", "dore"]'),
  ('Montre Chronographe Homme Cadran Noir', 'Montre masculine raffinée avec cadran noir soleillé, boîtier acier et bracelet en cuir véritable marron.', 210000, 15, 'Bijoux', '["https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=800&q=80"]', '["montre", "cuir", "chronographe"]'),
  ('Bague Anneau Fin Minimaliste Argent', 'Anneau fin épuré en argent sterling idéal à porter seul ou superposé pour un look discret.', 45000, 40, 'Bijoux', '["https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=800&q=80"]', '["bague", "argent", "minimaliste"]'),
  ('Pendentif Pierre Précieuse Saphir Bleu', 'Pendentif raffiné serti d''un saphir synthétique bleu royal et monté sur bélière argentée.', 95000, 20, 'Bijoux', '["https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=800&q=80"]', '["pendentif", "saphir", "bijou"]'),
  ('Bracelet Homme en Cuir Tressé & Acier', 'Bracelet double rang en cuir véritable tressé noir avec fermoir magnétique en acier brossé.', 55000, 28, 'Bijoux', '["https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=800&q=80"]', '["bracelet", "cuir", "homme"]'),
  ('Boîte à Bijoux Velours Compartimentée', 'Coffret de rangement élégant gainé de velours doux avec miroir intégré et tiroirs pour bagues et colliers.', 68000, 22, 'Bijoux', '["https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?auto=format&fit=crop&w=800&q=80"]', '["boite", "rangement", "velours"]'),
  ('Chaîne Maille Gourmette Plaqué Or', 'Chaîne élégante maille gourmette diamantée en plaqué or 750 avec fermoir mousqueton robuste.', 85000, 25, 'Bijoux', '["https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80"]', '["chaine", "or", "collier"]'),
  ('Sérum Hydratant Acide Hyaluronique', 'Sérum visage concentré à l''acide hyaluronique pur pour une hydratation intense et repulpante.', 42000, 55, 'Beauté', '["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80"]', '["serum", "hydratation", "soin"]'),
  ('Crème Nourrissante Visage & Éclat', 'Soin quotidien hydratant aux extraits botaniques naturels pour une peau douce, lumineuse et protégée.', 38000, 48, 'Beauté', '["https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80"]', '["creme", "visage", "beaute"]'),
  ('Rouge à Lèvres Velours Rouge Intense', 'Rouge à lèvres mat longue tenue offrant une couleur vibrante et une formule enrichie en huiles végétales.', 26000, 60, 'Beauté', '["https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=800&q=80"]', '["rouge", "levres", "maquillage"]'),
  ('Palette d''Ombres à Paupières Nude & Nacres', 'Palette de 12 teintes fards à paupières coordonnées mats et irisés, formule haute pigmentation facile à estomper.', 52000, 30, 'Beauté', '["https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80"]', '["palette", "yeux", "fard"]'),
  ('Huile d''Argan Pure Vierge 100ml', 'Huile végétale 100% pure pressée à froid, idéale pour nourrir visage, corps et cheveux secs.', 34000, 42, 'Beauté', '["https://images.unsplash.com/photo-1608248597359-00913959b85c?auto=format&fit=crop&w=800&q=80"]', '["huile", "argan", "naturel"]'),
  ('Mascara Volume & Allongement Noir Profond', 'Mascara regard intense avec brosse en silicone pour séparer les cils et apporter un volume spectaculaire.', 29000, 50, 'Beauté', '["https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?auto=format&fit=crop&w=800&q=80"]', '["mascara", "yeux", "cils"]'),
  ('Eau de Parfum Florale & Ambrée 50ml', 'Fragrance délicate mêlant des notes de jasmin, fleur d''oranger et vanille ambrée dans un flacon luxueux.', 98000, 25, 'Beauté', '["https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=80"]', '["parfum", "fragrance", "luxe"]'),
  ('Vernis à Ongles Brillance Miroir Rouge', 'Vernis à ongles longue durée tenue 7 jours, séchage rapide et fini ultra-brillant sans écaillement.', 15000, 70, 'Beauté', '["https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=800&q=80"]', '["vernis", "ongles", "manucure"]'),
  ('Kit Pinceaux de Maquillage Professionnel', 'Ensemble de 8 pinceaux de maquillage aux poils soyeux synthétiques avec étui de transport pratique.', 45000, 35, 'Beauté', '["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80"]', '["pinceaux", "maquillage", "accessoire"]'),
  ('Gel Nettoyant Visage Purifiant Moussant', 'Nettoyant doux sans savon qui élimine l''excès de sébum et les impuretés tout en préservant l''équilibre cutané.', 27000, 50, 'Beauté', '["https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&w=800&q=80"]', '["nettoyant", "visage", "purifiant"]'),
  ('Pneu 4 Saisons Haute Adhérence 205/55 R16', 'Pneumatique performant sur route sèche et mouillée avec faible résistance au roulement et confort acoustique.', 220000, 24, 'Auto', '["https://images.unsplash.com/photo-1578844251758-2f71da64c96f?auto=format&fit=crop&w=800&q=80"]', '["pneu", "auto", "securite"]'),
  ('Support Téléphone Voiture Magnétique Grille', 'Support magnétique puissant orientable à 360° pour fixation stable sur les grilles d''aération du véhicule.', 25000, 65, 'Auto', '["https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?auto=format&fit=crop&w=800&q=80"]', '["support", "smartphone", "voiture"]'),
  ('Chargeur Allume-Cigare USB-C Rapide 60W', 'Adaptateur voiture double port USB-A et USB-C Power Delivery pour recharger smartphones et tablettes à pleine vitesse.', 35000, 50, 'Auto', '["https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80"]', '["chargeur", "usb", "accessoire"]'),
  ('Kit de Nettoyage et Lustrage Carrosserie Auto', 'Pack complet d''entretien avec shampoing carrosserie déperlant, cire de lustrage et microfibres haute densité.', 58000, 30, 'Auto', '["https://images.unsplash.com/photo-1607860108855-64acf2078ed9?auto=format&fit=crop&w=800&q=80"]', '["nettoyage", "lavage", "carrosserie"]'),
  ('Aspirateur Voiture Portable Sans Fil Puissant', 'Mini aspirateur à main sans fil avec batterie rechargeable, filtre HEPA lavable et buses multifonctions.', 85000, 22, 'Auto', '["https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=800&q=80"]', '["aspirateur", "interieur", "auto"]'),
  ('Compresseur d''Air Pneus Digital 12V', 'Gonfleur électrique compact avec manomètre digital rétroéclairé et arrêt automatique à la pression souhaitée.', 110000, 18, 'Auto', '["https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&w=800&q=80"]', '["gonfleur", "compresseur", "pression"]'),
  ('Paire de Balais d''Essuie-Glace Silencieux', 'Balais d''essuie-glace plats aérodynamiques en caoutchouc naturel traité pour un essuyage parfait sans traces.', 42000, 40, 'Auto', '["https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80"]', '["essuie-glace", "pare-brise", "visibilite"]'),
  ('Organisateur de Coffre Pliable Renforcé', 'Sac de rangement de coffre à compartiments multiples modulables en tissu Oxford imperméable et résistant.', 48000, 35, 'Auto', '["https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80"]', '["coffre", "rangement", "organisation"]'),
  ('Câbles de Démarrage Batterie Renforcés 500A', 'Câbles de démarrage en cuivre pur 3 mètres avec pinces isolées renforcées pour véhicules essence et diesel.', 55000, 28, 'Auto', '["https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=800&q=80"]', '["cables", "batterie", "depannage"]'),
  ('Diffuseur Désodorisant Voiture Parfum Cuir', 'Diffuseur d''ambiance design à clipser sur la grille de ventilation avec recharge parfumée longue durée 60 jours.', 18000, 80, 'Auto', '["https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=800&q=80"]', '["desodorisant", "parfum", "interieur"]'),
  ('Huile d''Olive Vierge Extra Bio 750ml', 'Huile d''olive de première pression à froid, fruité vert équilibré aux arômes d''amande fraîche et d''herbe coupée.', 36000, 45, 'Alimentation', '["https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=800&q=80"]', '["huile", "olive", "bio"]'),
  ('Café en Grains Pur Arabica Torréfié 500g', 'Sélection de grains de café arabica d''altitude torréfiés artisanalement pour un expresso riche et onctueux.', 28000, 60, 'Alimentation', '["https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=800&q=80"]', '["cafe", "arabica", "boisson"]'),
  ('Miel Naturel Toutes Fleurs Pot 500g', 'Miel pur récolté traditionnellement, texture onctueuse et saveur florale délicate pour tartines et tisanes.', 22000, 50, 'Alimentation', '["https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80"]', '["miel", "naturel", "sucre"]'),
  ('Tablette de Chocolat Noir 70% Pur Cacao', 'Chocolat noir artisanal aux fèves de cacao sélectionnées avec soin, notes corsées et texture fondante.', 12000, 85, 'Alimentation', '["https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=800&q=80"]', '["chocolat", "gourmandise", "cacao"]'),
  ('Thé Vert Matcha Japonais Bio 100g', 'Poudre fine de thé vert matcha de cérémonie riche en antioxydants, idéale pour thés, lattes et pâtisseries.', 45000, 35, 'Alimentation', '["https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80"]', '["the", "matcha", "bio"]'),
  ('Mélange Noix & Fruits Secs Énergie 400g', 'Cocktail sain d''amandes, noix de cajou, noisettes, raisins secs et canneberges pour une collation énergétique.', 25000, 65, 'Alimentation', '["https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=800&q=80"]', '["noix", "fruits-secs", "snack"]'),
  ('Pâtes Italiennes Penne Rigate Artisanales 500g', 'Pâtes de blé dur tréfilées au bronze et séchées lentement pour une tenue parfaite et une sauce bien absorbée.', 14000, 90, 'Alimentation', '["https://images.unsplash.com/photo-1551462147-ff29053bfc14?auto=format&fit=crop&w=800&q=80"]', '["pates", "italie", "cuisine"]'),
  ('Granola Croustillant Avoine & Amandes Miel', 'Flocons d''avoine complets dorés au four avec graines de tournesol, amandes effilées et pointe de miel.', 21000, 40, 'Alimentation', '["https://images.unsplash.com/photo-1517093157656-b9ec80eb30e7?auto=format&fit=crop&w=800&q=80"]', '["granola", "cereales", "dejeuner"]'),
  ('Confiture Artisanale Fraise & Basilic 350g', 'Confiture cuite au chaudron de cuivre avec 65% de fruits entiers cueillis à maturité et une touche de basilic frais.', 18000, 48, 'Alimentation', '["https://images.unsplash.com/photo-1506802913710-40e2e66339c9?auto=format&fit=crop&w=800&q=80"]', '["confiture", "fruits", "fraise"]'),
  ('Gousses de Vanille Bourbon de Madagascar (Lot de 5)', 'Véritable vanille Bourbon de Madagascar affinée, gousses souples et grasses au parfum intense et vanilliné.', 50000, 35, 'Alimentation', '["https://images.unsplash.com/photo-1608686207856-001b95cf60ca?auto=format&fit=crop&w=800&q=80"]', '["vanille", "madagascar", "epices"]')
) as x(name,description,price,stock,category,images,tags)
join public.categories c on c.name=x.category
where not exists(select 1 from public.products p where p.name=x.name);

-- Après création du premier compte, rendez-le admin avec :
-- update public.profiles set role='admin' where email='votre-email-admin@example.com';

insert into storage.buckets(id,name,public) values('product-images','product-images',true) on conflict(id) do nothing;
drop policy if exists product_images_read on storage.objects;
create policy product_images_read on storage.objects for select using(bucket_id='product-images');
drop policy if exists product_images_admin_insert on storage.objects;
create policy product_images_admin_insert on storage.objects for insert to authenticated with check(bucket_id='product-images' and public.is_admin());
drop policy if exists product_images_admin_update on storage.objects;
create policy product_images_admin_update on storage.objects for update to authenticated using(bucket_id='product-images' and public.is_admin()) with check(bucket_id='product-images' and public.is_admin());
drop policy if exists product_images_admin_delete on storage.objects;
create policy product_images_admin_delete on storage.objects for delete to authenticated using(bucket_id='product-images' and public.is_admin());
