-- Me-Antsena / Supabase schema
-- Exécuter ce fichier dans Supabase Dashboard > SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text not null default '',
  last_name text not null default '',
  email text not null unique,
  phone text,
  role text not null default 'user' check (role in ('user','admin')),
  status text not null default 'active' check (status in ('active','suspended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text default '🏷️'
);
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  price numeric(14,2) not null check(price >= 0),
  stock integer not null default 0 check(stock >= 0),
  category_id bigint references public.categories(id) on delete set null,
  images jsonb not null default '[]'::jsonb,
  tags jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.addresses (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  label text not null default 'Livraison', street text not null, created_at timestamptz not null default now()
);
create table if not exists public.favorites (
  user_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(), primary key(user_id,product_id)
);
create table if not exists public.interactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  type text not null, value numeric(12,2), created_at timestamptz not null default now()
);
create table if not exists public.recommendations (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('collaborative','content','hybrid')),
  product_id bigint not null references public.products(id) on delete cascade,
  score numeric(12,6) not null default 0,
  created_at timestamptz not null default now(),
  unique(type, product_id)
);
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  rating integer not null check(rating between 1 and 5), comment text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,product_id)
);
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete restrict,
  address_id bigint references public.addresses(id) on delete set null,
  payment_method text, delivery_method text,
  status text not null default 'pending' check(status in ('pending','paid','shipped','delivered','cancelled')),
  total numeric(14,2) not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null, unit_price numeric(14,2) not null, quantity integer not null check(quantity > 0)
);

create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,first_name,last_name,email,phone)
  values(new.id,coalesce(new.raw_user_meta_data->>'first_name',''),coalesce(new.raw_user_meta_data->>'last_name',''),new.email,coalesce(new.raw_user_meta_data->>'phone',''))
  on conflict(id) do update set email=excluded.email;
  return new;
end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='admin' and status='active');
$$;

create or replace function public.admin_set_user_status(p_user_id uuid, p_status text) returns public.profiles
language plpgsql security definer set search_path=public as $$
declare v public.profiles;
begin
  if not public.is_admin() then raise exception 'Accès administrateur requis'; end if;
  if p_status not in ('active','suspended') then raise exception 'Statut invalide'; end if;
  update public.profiles set status=p_status,updated_at=now() where id=p_user_id returning * into v;
  if not found then raise exception 'Utilisateur introuvable'; end if;
  return v;
end; $$;
revoke all on function public.admin_set_user_status(uuid,text) from public;
grant execute on function public.admin_set_user_status(uuid,text) to authenticated;

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.addresses enable row level security;
alter table public.favorites enable row level security;
alter table public.interactions enable row level security;
alter table public.recommendations enable row level security;
alter table public.reviews enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select using (id=auth.uid() or public.is_admin());
drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles for update using (id=auth.uid()) with check (id=auth.uid());
revoke update on public.profiles from authenticated;
grant update(first_name,last_name,phone) on public.profiles to authenticated;

drop policy if exists categories_read on public.categories; create policy categories_read on public.categories for select using(true);
drop policy if exists categories_admin on public.categories; create policy categories_admin on public.categories for all using(public.is_admin()) with check(public.is_admin());

drop policy if exists products_read on public.products; create policy products_read on public.products for select using(true);
drop policy if exists products_admin on public.products; create policy products_admin on public.products for all using(public.is_admin()) with check(public.is_admin());

drop policy if exists addresses_own on public.addresses; create policy addresses_own on public.addresses for all using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin());
drop policy if exists favorites_own on public.favorites; create policy favorites_own on public.favorites for all using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists interactions_own on public.interactions; create policy interactions_own on public.interactions for all using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists interactions_admin_read on public.interactions; create policy interactions_admin_read on public.interactions for select using(public.is_admin());
drop policy if exists recommendations_read on public.recommendations; create policy recommendations_read on public.recommendations for select using(true);
drop policy if exists recommendations_admin on public.recommendations; create policy recommendations_admin on public.recommendations for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists reviews_read on public.reviews; create policy reviews_read on public.reviews for select using(true);
drop policy if exists reviews_write on public.reviews; create policy reviews_write on public.reviews for all using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists orders_read on public.orders; create policy orders_read on public.orders for select using(user_id=auth.uid() or public.is_admin());
drop policy if exists orders_admin_update on public.orders; create policy orders_admin_update on public.orders for update using(public.is_admin()) with check(public.is_admin());
drop policy if exists order_items_read on public.order_items; create policy order_items_read on public.order_items for select using(exists(select 1 from public.orders o where o.id=order_id and (o.user_id=auth.uid() or public.is_admin())));

create or replace function public.create_order(p_items jsonb,p_address_id bigint default null,p_payment_method text default null,p_delivery_method text default null)
returns public.orders language plpgsql security definer set search_path=public as $$
declare v_order public.orders; v_item jsonb; v_product public.products; v_qty integer; v_total numeric(14,2):=0;
begin
 if auth.uid() is null then raise exception 'Authentification requise'; end if;
 if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items)=0 then raise exception 'Panier vide'; end if;
 if p_address_id is not null and not exists(select 1 from public.addresses where id=p_address_id and user_id=auth.uid()) then raise exception 'Adresse invalide'; end if;
 insert into public.orders(user_id,address_id,payment_method,delivery_method,total) values(auth.uid(),p_address_id,p_payment_method,p_delivery_method,0) returning * into v_order;
 for v_item in select * from jsonb_array_elements(p_items) loop
   v_qty := (v_item->>'quantity')::integer;
   select * into v_product from public.products where id=(v_item->>'product_id')::bigint for update;
   if not found then raise exception 'Produit introuvable'; end if;
   if v_qty < 1 or v_qty > v_product.stock then raise exception 'Stock insuffisant pour %',v_product.name; end if;
   v_total := v_total + v_product.price * v_qty;
   insert into public.order_items(order_id,product_id,product_name,unit_price,quantity) values(v_order.id,v_product.id,v_product.name,v_product.price,v_qty);
   update public.products set stock=stock-v_qty,updated_at=now() where id=v_product.id;
 end loop;
 update public.orders set total=v_total where id=v_order.id returning * into v_order;
 return v_order;
exception when others then raise;
end; $$;

revoke all on function public.create_order(jsonb,bigint,text,text) from public;
grant execute on function public.create_order(jsonb,bigint,text,text) to authenticated;

insert into public.categories(name,icon) values
('Électronique','💻'),('Mode','👕'),('Maison','🏠'),('Sports','⚽'),('Livres','📚'),('Bijoux','💍'),('Beauté','💄'),('Auto','🚗'),('Alimentation','🛒') on conflict(name) do nothing;

insert into public.products(name,description,price,stock,category_id,images,tags)
select x.name,x.description,x.price,x.stock,c.id,x.images::jsonb,x.tags::jsonb from (values
('Casque Bluetooth SoundPro X1','Casque sans fil confortable avec réduction de bruit, autonomie longue durée et son équilibré.',120000,45,'Électronique','["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80"]','["audio","bluetooth","casque"]'),
('Sac à dos tendance','Sac à dos moderne, pratique et résistant pour les études, le travail et les sorties.',85000,30,'Mode','["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80"]','["sac","mode","quotidien"]'),
('Montre connectée Fit 3','Montre connectée avec suivi d’activité, notifications et autonomie optimisée.',110000,20,'Électronique','["https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=800&q=80"]','["montre","sport","smartwatch"]'),
('Lampe LED moderne','Lampe LED minimaliste idéale pour le bureau ou la chambre.',45000,60,'Maison','["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80"]','["lampe","bureau","maison"]'),
('Baskets Urban Run','Baskets légères pensées pour la marche, le running et un usage quotidien.',165000,18,'Sports','["https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80"]','["chaussures","sport","running"]'),
('Montre classique Élégance','Une montre classique au design intemporel.',98000,12,'Mode','["https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=800&q=80"]','["montre","élégance","mode"]'),
('Sneakers Nova','Sneakers confortables avec semelle souple et style urbain.',145000,25,'Sports','["https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=80"]','["sneakers","sport","mode"]'),
('Sac cuir Premium','Sac premium avec finition élégante et compartiments pratiques.',185000,8,'Mode','["https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=800&q=80"]','["cuir","sac","premium"]'),
('T-shirt Essential','T-shirt confortable en coton, facile à porter au quotidien.',55000,100,'Mode','["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80"]','["tshirt","mode","essentiel"]'),
('Clavier mécanique','Clavier mécanique compact pour le travail et le gaming.',135000,16,'Électronique','["https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80"]','["clavier","gaming","ordinateur"]')
) as x(name,description,price,stock,category,images,tags)
join public.categories c on c.name=x.category
where not exists(select 1 from public.products p where p.name=x.name);

-- Après création du premier compte, rendez-le admin avec :
-- update public.profiles set role='admin' where email='votre-email-admin@example.com';

insert into storage.buckets(id,name,public) values('product-images','product-images',true) on conflict(id) do nothing;
drop policy if exists product_images_read on storage.objects;
create policy product_images_read on storage.objects for select using(bucket_id='product-images');
drop policy if exists product_images_admin_insert on storage.objects;
create policy product_images_admin_insert on storage.objects for insert to authenticated with check(bucket_id='product-images' and public.is_admin());
drop policy if exists product_images_admin_update on storage.objects;
create policy product_images_admin_update on storage.objects for update to authenticated using(bucket_id='product-images' and public.is_admin()) with check(bucket_id='product-images' and public.is_admin());
drop policy if exists product_images_admin_delete on storage.objects;
create policy product_images_admin_delete on storage.objects for delete to authenticated using(bucket_id='product-images' and public.is_admin());
