import { Bell, Heart, HelpCircle, LogOut, MapPin, Moon, Package, RotateCcw, Settings, Shield, Sun, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import toast from "react-hot-toast";
import { useAuth } from "../context/AuthContext";
import { useFavorites } from "../context/FavoritesContext";
import { useOrders } from "../context/OrdersContext";
import { useSettings } from "../context/SettingsContext";
import { useTheme } from "../context/ThemeContext";
import ProductCard from "../components/ProductCard";
import { formatPrice } from "../utils/format";

export default function Profile(){
 const {user,logout}=useAuth(); const [params,setParams]=useSearchParams(); const [tab,setTab]=useState(params.get("tab")||"profile");
 useEffect(()=>{setTab(params.get("tab")||"profile")},[params]); if(!user)return null;
 const changeTab=k=>{setTab(k);setParams(k==="profile"?{}:{tab:k})};
 const items=[["profile","Mon profil",UserRound],["orders","Mes commandes",Package],["favorites","Favoris",Heart],["settings","Paramètres",Settings]];
 return <div className="container-app py-8"><div className="grid gap-6 lg:grid-cols-[260px_1fr]">
  <aside className="card h-fit p-4"><div className="rounded-2xl bg-gradient-to-br from-brand-100 to-pink-100 p-5 dark:from-brand-900/40 dark:to-pink-900/20"><div className="grid h-16 w-16 place-items-center rounded-full bg-white text-brand-500 shadow"><UserRound/></div><h2 className="mt-4 font-black">{user.name}</h2><p className="text-xs muted">{user.email}</p></div><nav className="mt-3 space-y-1">{items.map(([k,l,I])=><button key={k} onClick={()=>changeTab(k)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold ${tab===k?"bg-brand-50 text-brand-600 dark:bg-brand-900/30":"text-slate-500"}`}><I size={17}/>{l}</button>)}<button onClick={logout} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-red-500"><LogOut size={17}/> Déconnexion</button></nav></aside>
  <section>{tab==="profile"&&<ProfileTab user={user}/>} {tab==="orders"&&<Orders/>} {tab==="favorites"&&<Favorites/>} {tab==="settings"&&<SettingsTab/>}</section>
 </div></div>
}
function ProfileTab({user}){const {updateProfile}=useAuth(); const [name,setName]=useState(user.name||"");const [phone,setPhone]=useState(user.phone||"");const [address,setAddress]=useState(user.address||"Lot II A, Antananarivo");const [saving,setSaving]=useState(false);const save=async()=>{setSaving(true);try{await updateProfile({name:name.trim()||user.name,phone:phone.trim(),address:address.trim()});toast.success("Profil enregistré")}catch(err){toast.error(err.message)}finally{setSaving(false)}};return <div><p className="eyebrow">Compte</p><h1 className="mt-1 text-3xl font-black">Mon profil</h1><div className="card mt-6 p-6"><div className="grid gap-4 sm:grid-cols-2"><Field label="Nom complet" value={name} onChange={setName}/><Field label="Email" value={user.email} readOnly/><Field label="Téléphone" value={phone} onChange={setPhone}/><Field label="Rôle" value={user.role==="admin"?"Administrateur":"Client"} readOnly/></div><button onClick={save} disabled={saving} className="btn-primary mt-5">{saving?"Enregistrement...":"Enregistrer les modifications"}</button></div><div className="card mt-5 p-6"><div className="flex items-center gap-2"><MapPin size={18} className="text-brand-500"/><h2 className="font-black">Adresse principale</h2></div><input className="input mt-4" value={address} onChange={e=>setAddress(e.target.value)} placeholder="Votre adresse de livraison"/><p className="mt-2 text-xs muted">Cette adresse est sauvegardée avec votre profil.</p></div></div>}
function Field({label,value,onChange,readOnly}){return <div><label className="mb-2 block text-xs font-bold">{label}</label><input readOnly={readOnly} className="input" value={value||""} onChange={e=>onChange?.(e.target.value)}/></div>}
function Orders(){const {userOrders}=useOrders();return <div><p className="eyebrow">Historique</p><h1 className="mt-1 text-3xl font-black">Mes commandes</h1><div className="mt-6 space-y-3">{userOrders.length?userOrders.map(o=><div key={o.id} className="card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><b>Commande #{o.id.replace("CMD-","")}</b><p className="text-xs muted">{o.date}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${o.status==="Livrée"?"bg-emerald-100 text-emerald-700":o.status==="Annulée"?"bg-red-100 text-red-600":"bg-orange-100 text-orange-700"}`}>{o.status}</span><b className="text-brand-600">{formatPrice(o.total)}</b></div>{o.items?.length>0&&<div className="mt-4 flex gap-3">{o.items.map(i=><img key={i.id} src={i.image} alt={i.name} className="h-14 w-14 rounded-xl object-cover"/>)}</div>}</div>):<div className="card p-10 text-center"><Package className="mx-auto text-slate-300"/><p className="mt-3 font-bold">Aucune commande</p></div>}</div></div>}
function Favorites(){const {favorites}=useFavorites();return <div><p className="eyebrow">Sauvegardés</p><h1 className="mt-1 text-3xl font-black">Favoris</h1><div className="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-3">{favorites.length?favorites.map(p=><ProductCard key={p.id} product={p}/>):<div className="card col-span-full p-10 text-center"><Heart className="mx-auto text-slate-300"/><p className="mt-3 font-bold">Aucun favori</p></div>}</div></div>}
function SettingsTab(){const {settings,update,reset}=useSettings();const {theme,toggleTheme}=useTheme();const rows=[{title:"Notifications",text:"Alertes de commandes et recommandations",icon:Bell,key:"notifications"},{title:"Offres personnalisées",text:"Recevoir les promotions adaptées",icon:Heart,key:"marketing"}];return <div><div className="flex items-end justify-between"><div><p className="eyebrow">Préférences</p><h1 className="mt-1 text-3xl font-black">Paramètres</h1></div><button onClick={()=>{reset();toast.success("Paramètres réinitialisés")}} className="btn-secondary text-xs"><RotateCcw size={15}/> Réinitialiser</button></div><div className="card mt-6 divide-y divide-slate-100 dark:divide-white/10">{rows.map(({title,text,icon:Icon,key})=><div key={key} className="flex items-center justify-between gap-4 p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-900/30"><Icon size={18}/></span><div><b className="text-sm">{title}</b><p className="mt-1 text-xs muted">{text}</p></div></div><button onClick={()=>update(key,!settings[key])} className={`relative h-7 w-12 rounded-full transition ${settings[key]?"bg-brand-500":"bg-slate-300 dark:bg-slate-600"}`} aria-label={`Changer ${title}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${settings[key]?"left-6":"left-1"}`}/></button></div>)}
 <div className="flex items-center justify-between p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-900/30">{theme==="dark"?<Moon size={18}/>:<Sun size={18}/>}</span><div><b className="text-sm">Thème</b><p className="mt-1 text-xs muted">{theme==="dark"?"Mode sombre":"Mode clair"}</p></div></div><button onClick={toggleTheme} className="btn-secondary px-4 py-2 text-xs">Changer</button></div>
 <div className="flex items-center justify-between p-5"><div><b className="text-sm">Langue</b><p className="mt-1 text-xs muted">Interface actuelle : {settings.language}</p></div><select value={settings.language} onChange={e=>{update("language",e.target.value);toast.success("Langue enregistrée")}} className="input w-auto"><option>Français</option><option>Malagasy</option><option>English</option></select></div>
 <div className="flex items-center justify-between p-5"><div className="flex items-center gap-3"><Shield className="text-brand-500"/><div><b className="text-sm">Confidentialité</b><p className="mt-1 text-xs muted">Gestion des préférences de données</p></div></div><button onClick={()=>toast("Vos données locales restent dans ce navigateur dans cette version simulée.")} className="btn-secondary px-4 py-2 text-xs">Gérer</button></div>
 <div className="flex items-center justify-between p-5"><div className="flex items-center gap-3"><HelpCircle className="text-brand-500"/><div><b className="text-sm">Aide & Support</b><p className="mt-1 text-xs muted">Questions sur votre compte ou vos commandes</p></div></div><button onClick={()=>toast("Support : support@me-antsena.mg")} className="btn-secondary px-4 py-2 text-xs">Contacter</button></div>
 </div></div>}
